### ISSUE TITLE
Cant Make Any New Changes

### ISSUE THREAD

**Issue by Yui007** [Crivella/ocr_extension#6]
Hi, First of all thank you so much for such an amazing program, I was looking for something like this for a long time,So thank you so much. Now the issue i am currently facing is when i make changes to the background.js or content.js code and run Npm install and then Npm run build, it overwrites my changes with your old changes , why is that , is there no way to fix that because right now i am working to add a new feature Always OCR so that it run always so i dont have to press it to on whenever i open new manga page or anything. Again Thank you so much for such an amazing Program

**Comment by Crivella** [comment]
Thanks for the appreciation.

Unless you are modifying the `package.json` you should run `npm install` only once at the beginning to install all the dependencies (it will create/populate the `node_modules` folder under your project).

The fact that running `npm build` is overriding your changes leads me to think you are modifying the files under `extension/dist`. If that is the case, you should be modifying the files under `src` as those are the actual source files (the one under dist are the one packaged by webpack when you run `npm build`).
If that is not the case I will need more info to understand what is happening.

**Comment by Yui007** [comment]
no i am making changes to the files under src folder

**Comment by Crivella** [comment]
So what you mean is that the files under dist do not have the changes that you put under src? (That would be very weird)

Or are you referring to the extension behavior in the browser?
If that is the case make sure to reload the temporary extension after you made changes by clicking on
![image](https://github.com/user-attachments/assets/3a4a5a1f-59e6-4f53-a962-44baa39934f3)
Also note that if you have the temporary extension loaded + the one installed from the Mozilla repository should see 2 icons in the bar and popup menu. Make sure to use the right one or disable the official one so you can work more easily

**Comment by Yui007** [comment]
So what you mean is that the files under dist do not have the changes that you put under src? Yes the dist folder files doesnot have the changes made in the src folder -- after running npm run build:prod

**Comment by Crivella** [comment]
Umh not sure what could be happening, that is how i work myself. Make changes to src and than build to get the packed version under dist.
Without being able to reproduce this myself it is gonna be difficult to understand what is going on

Try not using the `prod`, as that gives you the minified version that makes it harder to understand what is going on

Regarding the `background.js` script, that should not be touched by the build stuff.

For `content.js`, you will see a bunch of stuff on top which is webpack including all the stuff needed to replace the imports.
In a pinch if you are only modifying the content.js and none of the imported functions you can just add the changes of your content.js at the end of the `dist` one where (without prod) you should see basically the same stuff

**Comment by Yui007** [comment]
ok i just tried npm run build without prod and it worked perfectly i can see my code but with prod it didn't work

**Comment by Crivella** [comment]
K still weird but happy it is working (closing the issue but feel free to reopen or open a new one if something else comes up).

Regarding the original topic of what you want to include if it ends up something you think more people would like to use, consider making a PR  ;P

**Comment by Yui007** [comment]
Thanks For Helping Me Out and Regarding the new feature if i succeeded in implementing it then sure i will 100% make a PR
